apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-pod-dev
  labels:
    app: nginx-pod-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: nginx-pod-dev
    name: do-syd1-k8s-1-24-4-do-0-syd1-1669343102356
  source:
    repoURL: https://github.com/nztommo/cd-five-mins-local.git
    targetRevision: main
    path: ./k8s-resources/nginx-pod/dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
